### ISSUE TITLE
Crashes on android

### ISSUE THREAD

**Issue by diver2** [mchome/flutter_statusbarcolor#14]
I am testing this on a samsung s6. 
Just adding the flutter_statusbarcolor: to the pubspec.yaml file makes the app impossible to run in the cellphone. (did not add any code, not even an import)
Weirdly, no error is given for me. 
(Built build/app/outputs/apk/debug/app-debug.apk 
then it tries to install and open it in cellphone, then it says "nameofapp" has stopped
issue also happens with simulator (nexus5 on API 26 Android 8.0)

If you need any further info, I'm happy to pass it...

It works fine on ios (tesing on an iphone6)

**Comment by mchome** [comment]
Try to remove `build` folder and build again.

**Comment by diver2** [comment]
That did the trick. Thanks.
