### ISSUE TITLE
Can gradle plugin be upgraded?

### ISSUE THREAD

**Issue by psyanite** [mchome/flutter_statusbarcolor#17]
When I change `build.gradle` to use `classpath 'com.android.tools.build:gradle:3.3.0'` I experience this error when running `flutter run`:
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_statusbarcolor' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```

and probably need to downgrade to 3.2.1 as per https://stackoverflow.com/questions/54693595/flutter-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1

Is it possible to upgrade?

**Comment by mchome** [comment]
Hi, what version of this plugin are you using? `v0.2.0` should fix this.

**Comment by psyanite** [comment]
Thanks for the quick response. I will double check. 

I think you were right, seems like it's working now.
