### ISSUE TITLE
Black Foreground NOT working on ios 12.1

### ISSUE THREAD

**Issue by malnafei** [mchome/flutter_statusbarcolor#19]
I need to set a grey background for a status bar with black color for foreground but still not working.
The status bar background color chnaged to gery but the foreground still with white color.
output:
<img width="410" alt="Screen Shot 2019-03-22 at 6 07 09 PM" src="https://user-images.githubusercontent.com/15148391/54828478-b595a280-4ccd-11e9-9191-b5dbad6313b0.png">

My code:
```
 await FlutterStatusbarcolor.setStatusBarColor(Colors.grey[100]);

 await FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
```

My flutter doctor:
`[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.2.1 at /Users/xx/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • iPhone 8  • ios • iOS 12.1.4
    • iPhone 8  • ios • iOS 12.1 (simulator)`

**Comment by tapizquent** [comment]
Any updates on this???

**Comment by malnafei** [comment]
> Any updates on this???

Hello @tapizquent , Actually I figure out that you can set the status bar icons and text to black by using `brightness: Brightness.light` on the AppBar widget.

Example from my app:

```
appBar: new AppBar(
  brightness: Brightness.light, //Make the the status bar icons dark.
  backgroundColor: Colors.white,
  elevation: 0.0,

  ...
),
```

**Comment by tapizquent** [comment]
> > Any updates on this???
> 
> Hello @tapizquent , Actually I figure out that you can set the status bar icons and text to black by using `brightness: Brightness.light` on the AppBar widget.
> 
> Example from my app:
> 
> ```
> appBar: new AppBar(
>   brightness: Brightness.light, //Make the the status bar icons dark.
>   backgroundColor: Colors.white,
>   elevation: 0.0,
> 
>   ...
> ),
> ```

This does not work on the Stable channel, though. And beta channel currently has a lot of bugs I can’t really afford to incur, such as bold text not being displayed properly.
