### ISSUE TITLE
Can't build release mode in android

### ISSUE THREAD

**Issue by endigo** [mchome/flutter_statusbarcolor#20]
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :flutter_statusbarcolor.                 
     Required by:                                                       
         project :app                                                   
      > java.lang.NullPointerException (no error message)

**Comment by mchome** [comment]
Hi, what's your gradle version, try to upgrade your gradle version in
`android\gradle\wrapper\gradle-wrapper.properties`.

**Comment by endigo** [comment]
It's 4.10

```
#Sat Mar 09 16:28:18 ULAT 2019
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
```

**Comment by endigo** [comment]
Upgrade gradle  to 4.10.2 solved
