### ISSUE TITLE
Null check condition missing in the plugin

### ISSUE THREAD

**Issue by kazi41571** [mchome/flutter_statusbarcolor#25]
I am facing a crash in my app because of a missing null condition in your plugin. 
You have to add the below condition at the top of your plugin so that the headless check is done before the plugin is used.

Check the registerWith (and associated plugin constructor) for usage of registrar.activity(). Plugin's should first do a != null check before using it

For example, flutter_statusbarcolor is not checking if registrar.activity() != null before using it.

It should be doing this:
```
fun registerWith(registrar: Registrar): Unit {
            val channel = MethodChannel(registrar.messenger(), "plugins.fuyumi.com/statusbar")
+            if (registrar.activity() != null) {
                  channel.setMethodCallHandler(FlutterStatusbarcolorPlugin(registrar.activity()))
+            }
        }
```
Add the two lines marked with + in your plugin.

**Comment by mchome** [comment]
Try `0.2.1` :)
