### ISSUE TITLE
Open Dialog opacity change

### ISSUE THREAD

**Issue by jfdeveloper92** [mchome/flutter_statusbarcolor#28]
When setting the status bar and navigation bar colors the opacity when opening dialogs ignores the status bar and nav bars. Its expected that these would appear faded also. I have attached a screenshot of my result and one of the expected behavior.
![1773519519](https://user-images.githubusercontent.com/25892064/60862308-c584b400-a1e2-11e9-9230-e9683e99f744.png)

![Screenshot_20190709-003810](https://user-images.githubusercontent.com/25892064/60862161-5d35d280-a1e2-11e9-9897-8fd3ccfc6dda.png)

**Comment by amitkhairnar44** [comment]
@jfdeveloper92 I had same issue and it was solved when i used 
```dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(statusBarColor: Colors.transparent));
```

**Comment by jfdeveloper92** [comment]
@amitkhairnar44 are you using the white status bar? I did this and my icons are also white for some reason. I am using 

FlutterStatusbarcolor.setNavigationBarColor(Colors.white);
  FlutterStatusbarcolor.setNavigationBarWhiteForeground(false);
  FlutterStatusbarcolor.setStatusBarColor(Colors.white);
  FlutterStatusbarcolor.setStatusBarWhiteForeground(false);

**Comment by amitkhairnar44** [comment]
@jfdeveloper92 I'm not using white status bar. If your AppBar's color is white then no need to set white background in status bar. Just set it transparent using
```dart
FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
```

**Comment by amitkhairnar44** [comment]
Or see this example code
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  Key key = new UniqueKey();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      key: key,
      title: 'Example',
      home: new HomePage(),
    );
  }

  @override
  didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _changeStatusBarColor();
    }
    super.didChangeAppLifecycleState(state);
  }

  @override
  dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _changeStatusBarColor();
  }
  _changeStatusBarColor() async {
    await FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
    SystemChrome.setSystemUIOverlayStyle(
        SystemUiOverlayStyle(statusBarColor: Colors.transparent));
  }
}

```

**Comment by jfdeveloper92** [comment]
@amitkhairnar44  Thanks. Do you know of a way to set the screen fullscreen while keeping these settings? Im currently using the below code to make the screen full screen while on landscape. However with this code it is ignoring the status bar color.

 if (MediaQuery
        .of(context)
        .orientation == Orientation.landscape) {
      SystemChrome.setEnabledSystemUIOverlays([]);
    } else {
      SystemChrome.setEnabledSystemUIOverlays(
          [SystemUiOverlay.bottom, SystemUiOverlay.top]);
    }

**Comment by amitkhairnar44** [comment]
@jfdeveloper92 In portrait or landscape?

**Comment by jfdeveloper92** [comment]
@amitkhairnar44  well im wanting the app to go full screen in landscape then go back to normal on in portrait. Its a video app so im wanting the video to go full screen when you go landscape.

**Comment by jfdeveloper92** [comment]
also while keeping the statusbar color
