### ISSUE TITLE
status bar foreground disappears when turning back from the desktop.

### ISSUE THREAD

**Issue by blackredscarf** [mchome/flutter_statusbarcolor#29]
Status bar foreground disappears when turning back from the desktop in Android.
```
FlutterStatusbarcolor.setStatusBarColor(theme.scaffoldBackgroundColor);
FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
```
There is nothing in the status bar foreground.

**Comment by mchome** [comment]
Try [example app](https://github.com/mchome/flutter_statusbarcolor/blob/master/example/lib/main.dart), it should solve this problem.

**Comment by blackredscarf** [comment]
@mchome Thank you. It works.
