### ISSUE TITLE
Not working in iOS 13+ Dark mode

### ISSUE THREAD

**Issue by kleinpetr** [mchome/flutter_statusbarcolor#38]
When I have set the dark mode on ios, color not working

`FlutterStatusbarcolor.setStatusBarWhiteForeground(false);
`
![image](https://user-images.githubusercontent.com/17269309/68897710-5a1d9680-072e-11ea-9048-cb46d22fb0b2.png)

**Comment by mchome** [comment]
Hi, did you try the git version?

**Comment by kleinpetr** [comment]
@mchome yes. the master is working. When do you will push to stable?

**Comment by mchome** [comment]
`v0.2.3` uploaded!
