### ISSUE TITLE
Error No implementation found for method setstatusbarcolor on 

### ISSUE THREAD

**Issue by ejabu** [mchome/flutter_statusbarcolor#4]
E/flutter ( 5392): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 5392): MissingPluginException(No implementation found for method setstatusbarcolor on channel plugins.fuyumi.com/statusbar)
E/flutter ( 5392): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 5392): <asynchronous suspension>
E/flutter ( 5392): #1      FlutterStatusbarcolor.setStatusBarColor (package:flutter_statusbarcolor/flutter_statusbarcolor.dart:11:16)

should I change my android app name to com.fuyumi.flutterstatusbarcolor ?

How to use it inside completely new Flutter Project ? 

best regards

**Comment by mchome** [comment]
Umm, i cant reproduce this error.

install:

1. type "flutter new testme" (the app name will be "com.example.testme")
2. add "flutter_statusbarcolor: any" to testme/pubspec.yaml
3. copy my plugin's example/lib/main.dart to testme/lib/main.dart
4. in testme folder type "flutter run"
Works fine.

uninstall:

0. stop the app
1. remove "flutter_statusbarcolor: any" in testme/pubspec.yaml
2. revert the testme/lib/main.dart
3. in testme folder type "flutter run"
Works fine too.

**Comment by ejabu** [comment]
It works well now for me. Thanks !

Presumably, it was me forgot to stop and start the project again on gradle
