### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by MarcusCambio** [mchome/flutter_statusbarcolor#43]
Could not get this to work on Android, but then I saw that there is a PR that has been waiting to be merged for three weeks that did solve it: https://github.com/mchome/flutter_statusbarcolor/pull/42

How about merging it?

**Comment by mchome** [comment]
Can you confirm that pr fix your issue?

**Comment by MarcusCambio** [comment]
To be sure, I changed my dependency back to your master, and it actually works there too now, so no I can't confirm. Thanks anyway.

**Comment by janoschp** [comment]
@mchome I can confirm that the PR fixes this issue. I used the master version of your library and sometimes it works under Android but most fo the time it doesn't. I tested the PR version https://github.com/mchome/flutter_statusbarcolor/pull/42 and now setting the statusbar color always works. I suppose that in your master version the activity reference somehow gets lost and is therefore null, in the PR version this is fixed so it would be great if you could merge the PR.

**Comment by janoschp** [comment]
nvm it's actually buggy in the master version as well as the PR verion **sigh**
