### ISSUE TITLE
iOS 12.1 Build errors

### ISSUE THREAD

**Issue by workerbee22** [mchome/flutter_statusbarcolor#8]
Flutter v1.0.0 and building for iOS 12.1. See errors in image below at console:

<img width="1571" alt="ios_error" src="https://user-images.githubusercontent.com/5154664/50042700-ac87aa80-00ba-11e9-8e56-60a07574002e.png">

**Comment by mchome** [comment]
Try https://github.com/mchome/flutter_statusbarcolor/commit/f0949cdf54fadddb34fef2b8e2b3537e6a4ab2b3 with this setup:
https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by mchome** [comment]
`v0.1.3` landed :)
