### ISSUE TITLE
FlutterStatusbarcolor.setStatusBarWhiteForeground(false) being automatically reverted to true moments after successfully being set false

### ISSUE THREAD

**Issue by jonas-zebari** [mchome/flutter_statusbarcolor#9]
Main main method:
```dart
void main() {
  FlutterStatusbarcolor.setNavigationBarColor(Colors.white);
  FlutterStatusbarcolor.setNavigationBarWhiteForeground(false);
  FlutterStatusbarcolor.setStatusBarColor(Colors.white);
  FlutterStatusbarcolor.setStatusBarWhiteForeground(false); // automatically gets reverted even with empty project
  runApp(Messages());
}
```

After hot restarting and/or full restarting, the color of the status bar icons goes from dark to light. I will provide any additional informationt that I can just let me know, thanks.

**Comment by mchome** [comment]
Yeah, the status bar icons get reverted if the app lifecycle changed.
You can try example app. Flutter's WidgetsBindingObserver can fix this.

**Comment by jonas-zebari** [comment]
To be clear, the order of operation here is not Successful changing of color -> hot restart -> color reverted. I added this code, restarted, the colors went dark for less than a second and then, without me doing anything at all, the changed back to white.

**Comment by mchome** [comment]
Umm, try
```dart
Timer(Duration(seconds: 2), () => FlutterStatusbarcolor.setStatusBarWhiteForeground(false));
```

**Comment by jonas-zebari** [comment]
That worked but I don't understand why :(

**Comment by quetool** [comment]
@mchome that works fine but it is a workaround... Why is this happening?

**Comment by mchome** [comment]
@quetool  It's quite weird, i don't know either. :laughing:

**Comment by sgehrman** [comment]
I'm seeing this too. I'll try the timer.  I'm only seeing it on the Pixel Tablet simulator.  The phone and phone simulator work fine.  Test it on a tablet with Android 10.
